Update working directory and enhance test file discovery (#33)
## Description

This pull request includes several updates to the GitHub Actions
workflow configuration and documentation. The changes primarily focus on
enhancing test result outputs and adding a new test job.

Key changes include:

### Workflow Configuration Updates:
*
[`.github/workflows/Action-Test.yml`](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4L24-R28):
Added new outputs (`Executed` and `Result`) for all test jobs and
introduced a new job `ActionTest1SimpleExecutionFailure`. Updated the
job dependencies accordingly.
[[1]](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4L24-R28)
[[2]](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4L47-R54)
[[3]](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4R73-R108)
[[4]](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4L95-R135)
[[5]](diffhunk://#diff-a12ae5c885b0673c0ff6f70c2670886907590d624626e07da4c52e01aeaf56a4R159)
*
[`.github/linters/.jscpd.json`](diffhunk://#diff-557094e283c00b23265c1c75872f41c6b1a524a00f0d99dd68ebd22cb63bfdd6L7-R8):
Updated the ignore patterns to include
`**/.github/workflows/Action-Test**`.

### Documentation Updates:
*
[`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L161-R187):
Updated the test outcome section to include new output fields
(`Executed`, `Result`, `PassedCount`, `FailedCount`, `SkippedCount`,
`InconclusiveCount`, `NotRunCount`, `TotalCount`). Also updated the
example workflow to use `PSModule/Invoke-Pester@v3`.
[[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L161-R187)
[[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L232-R239)
[[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L256-R263)

### Other Minor Changes:
*
[`.github/workflows/Auto-Release.yml`](diffhunk://#diff-d3f6900ee5159d4bc4ba6d893e2dd8443c2691b0490d7351cffbd7a37ed8d95aL33-L34):
Removed the `GITHUB_TOKEN` environment variable from the `Auto-Release`
job.

## Type of change

<!-- Use the check-boxes [x] on the options that are relevant. -->

- [ ] 📖 [Docs]
- [ ] 🪲 [Fix]
- [ ] 🩹 [Patch]
- [ ] ⚠️ [Security fix]
- [ ] 🚀 [Feature]
- [ ] 🌟 [Breaking change]

## Checklist

<!-- Use the check-boxes [x] on the options that are relevant. -->

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -205,7 +205,57 @@ inputs:
   WorkingDirectory:
     description: The working directory where the script will run from.
     required: false
-    default: ${{ github.workspace }}
+    default: '.'
+
+outputs:
+  Outcome:
+    description: |
+      The outcome of the test run.
+    value: ${{ steps.test.outcome }}
+  Conclusion:
+    description: |
+      The conclusion of the test run.
+    value: ${{ steps.test.conclusion }}
+  Executed:
+    description: |
+      Whether tests were executed.
+    value: ${{ steps.status.outputs.Executed }}
+  Result:
+    description: |
+      Overall result of the Pester test run (e.g., Passed, Failed).
+    value: ${{ steps.test.outputs.Result }}
+  FailedCount:
+    description: |
+      Number of failed tests.
+    value: ${{ steps.test.outputs.FailedCount }}
+  FailedBlocksCount:
+    description: |
+      Number of failed blocks.
+    value: ${{ steps.test.outputs.FailedBlocksCount }}
+  FailedContainersCount:
+    description: |
+      Number of failed containers.
+    value: ${{ steps.test.outputs.FailedContainersCount }}
+  PassedCount:
+    description: |
+      Number of passed tests.
+    value: ${{ steps.test.outputs.PassedCount }}
+  SkippedCount:
+    description: |
+      Number of skipped tests.
+    value: ${{ steps.test.outputs.SkippedCount }}
+  InconclusiveCount:
+    description: |
+      Number of inconclusive tests.
+    value: ${{ steps.test.outputs.InconclusiveCount }}
+  NotRunCount:
+    description: |
+      Number of tests not run.
+    value: ${{ steps.test.outputs.NotRunCount }}
+  TotalCount:
+    description: |
+      Total count of tests.
+    value: ${{ steps.test.outputs.TotalCount }}
 
 runs:
   using: composite
@@ -268,14 +318,16 @@ runs:
           # Invoke-Pester (init)
           ${{ github.action_path }}/scripts/init.ps1
 
-    - name: Invoke-Pester
+    - name: Invoke-Pester (exec)
       shell: pwsh
       continue-on-error: true
       working-directory: ${{ inputs.WorkingDirectory }}
       env:
         PSMODULE_INVOKE_PESTER_INPUT_ReportAsJson: ${{ inputs.ReportAsJson }}
       id: test
-      run: ${{ github.action_path }}/scripts/main.ps1
+      run: |
+        # Invoke-Pester (exec)
+        ${{ github.action_path }}/scripts/exec.ps1
 
     - name: Upload test results - [${{ steps.test.outputs.TestSuiteName }}-TestResults]
       uses: actions/upload-artifact@v4
@@ -297,10 +349,39 @@ runs:
 
     - name: Status
       shell: pwsh
+      id: status
       working-directory: ${{ inputs.WorkingDirectory }}
+      env:
+        PSMODULE_INVOKE_PESTER_INTERNAL_Executed: ${{ steps.test.outputs.Executed }}
+        PSMODULE_INVOKE_PESTER_INTERNAL_Outcome: ${{ steps.test.outcome }}
+        PSMODULE_INVOKE_PESTER_INTERNAL_Conclusion: ${{ steps.test.conclusion }}
       run: |
-        $outcome = '${{ steps.test.outcome }}'
-        Write-Host "outcome: [$outcome]"
+        # Status
+        $PSStyle.OutputRendering = 'Ansi'
+        $executed = $env:PSMODULE_INVOKE_PESTER_INTERNAL_Executed -eq 'true'
+        $outcome = $env:PSMODULE_INVOKE_PESTER_INTERNAL_Outcome
+        $conclusion = $env:PSMODULE_INVOKE_PESTER_INTERNAL_Conclusion
+
+        "Executed=$executed" >> $env:GITHUB_OUTPUT
+
+        [PSCustomObject]@{
+          Executed = $executed
+          Outcome = $outcome
+          Conclusion = $conclusion
+        } | Format-List | Out-String
+
+        # If the tests did not execute, exit with a failure code
+        if ($executed -ne 'true') {
+          Write-Error "Tests did not execute."
+          exit 1
+        }
+        # If the outcome is not success, exit with a failure code
         if ($outcome -ne 'success') {
+          Write-Error "Tests did not pass."
+          exit 1
+        }
+        # If the conclusion is not success
+        if ($conclusion -ne 'success') {
+          Write-Error "Tests did not pass."
           exit 1
         }
