🌟 [Major]: Output cleanup + Fix test name expansion in summary (#12)
## Description

🌟 This pull request is a breaking change as it changes how you would
determine if the tests are successful or not. Previously this was done
with a `Passed` output, but is now just relying on the `outcome` and
`conclusion` properties of the test step. Together with
`continue-on-error` it creates a full solution for how to work with
failing tests. Don't use `continue-on-error` if you want the workflow to
stop, then and there, or use it with `conclusion` to gather tests and
make a decision based on more criteria.

### Fixing the summary

This pull request started as an attempt to just fix expansion of test
items in the Step Summary, but became more of an overhaul of the
functionality. This effort resulted in the creation of the `Markdown`
module that creates a DSL for writing markdown documents. The function
to traverse and create the summary structure was also heavily simplified
by following the hierarchy of objects in a `Pester.Run` class, resulting
in a recursive function that will also make it easier to add
functionality to it later.

- Fixes #9 

This could have been made simpler by just having "Children" as a
property of every object, but its called different and pretty much
achieves the same. `Invoke-Pester` returns a `Pester.Run`, a run has a
list of `Pester.Container` on the property `Container`. Containers have
`Pester.Block` on a property called `Blocks`. Blocks have
`Pester.Blocks` or `Pester.Test` objects on the property `Order`.

```mermaid
graph LR
    Run --> Container
    Container --> Blocks
    Blocks --> Order
    Order --> Test
    Order --> Blocks
```

## Type of change

<!-- Use the check-boxes [x] on the options that are relevant. -->

- [ ] 📖 [Docs]
- [ ] 🪲 [Fix]
- [ ] 🩹 [Patch]
- [ ] ⚠️ [Security fix]
- [ ] 🚀 [Feature]
- [x] 🌟 [Breaking change]

## Checklist

<!-- Use the check-boxes [x] on the options that are relevant. -->

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

diff --git a/.github/workflows/Action-Test.yml b/.github/workflows/Action-Test.yml
--- a/.github/workflows/Action-Test.yml
+++ b/.github/workflows/Action-Test.yml
@@ -38,10 +38,7 @@ jobs:
         shell: pwsh
         run: |
           Write-Host "Outcome: ${{ steps.action-test.outcome }}"
-          # Set-GitHubOutput -Name "outcome" -Value '${{ steps.action-test.outcome }}'
-
           Write-Host "Conclusion: ${{ steps.action-test.conclusion }}"
-          # Set-GitHubOutput -Name "conclusion" -Value '${{ steps.action-test.conclusion }}'
 
   ActionTest1SimpleFailure:
     name: Action-Test - [1-Simple-Failure]
@@ -65,10 +62,7 @@ jobs:
         shell: pwsh
         run: |
           Write-Host "Outcome: ${{ steps.action-test.outcome }}"
-          # Set-GitHubOutput -Name "outcome" -Value '${{ steps.action-test.outcome }}'
-
           Write-Host "Conclusion: ${{ steps.action-test.conclusion }}"
-          # Set-GitHubOutput -Name "conclusion" -Value '${{ steps.action-test.conclusion }}'
 
   ActionTest2Standard:
     name: Action-Test - [2-Standard]
@@ -92,10 +86,7 @@ jobs:
         shell: pwsh
         run: |
           Write-Host "Outcome: ${{ steps.action-test.outcome }}"
-          # Set-GitHubOutput -Name "outcome" -Value '${{ steps.action-test.outcome }}'
-
           Write-Host "Conclusion: ${{ steps.action-test.conclusion }}"
-          # Set-GitHubOutput -Name "conclusion" -Value '${{ steps.action-test.conclusion }}'
 
   ActionTest3Advanced:
     name: Action-Test - [3-Advanced]
@@ -118,10 +109,7 @@ jobs:
         shell: pwsh
         run: |
           Write-Host "Outcome: ${{ steps.action-test.outcome }}"
-          # Set-GitHubOutput -Name "outcome" -Value '${{ steps.action-test.outcome }}'
-
           Write-Host "Conclusion: ${{ steps.action-test.conclusion }}"
-          # Set-GitHubOutput -Name "conclusion" -Value '${{ steps.action-test.conclusion }}'
 
   CatchJob:
     name: "Catch Job - Aggregate Status"
@@ -133,92 +121,103 @@ jobs:
     if: always()
     runs-on: ubuntu-latest
     steps:
-      - name: "Display Aggregated Results as a Table"
-        shell: pwsh
-        run: |
-          # Build an array of objects for each job
-          $ActionTest1SimpleOutcome = "${{ needs.ActionTest1Simple.outputs.outcome }}"
-          $ActionTest1SimpleExpectedOutcome = "success"
-          $ActionTest1SimpleOutcomeResult = $ActionTest1SimpleOutcome -eq $ActionTest1SimpleExpectedOutcome
-          $ActionTest1SimpleConclusion = "${{ needs.ActionTest1Simple.outputs.conclusion }}"
-          $ActionTest1SimpleExpectedConclusion = "success"
-          $ActionTest1SimpleConclusionResult = $ActionTest1SimpleConclusion -eq $ActionTest1SimpleExpectedConclusion
-          $ActionTest1SimpleFailureOutcome = "${{ needs.ActionTest1SimpleFailure.outputs.outcome }}"
-          $ActionTest1SimpleFailureExpectedOutcome = "failure"
-          $ActionTest1SimpleFailureOutcomeResult = $ActionTest1SimpleFailureOutcome -eq $ActionTest1SimpleFailureExpectedOutcome
-          $ActionTest1SimpleFailureConclusion = "${{ needs.ActionTest1SimpleFailure.outputs.conclusion }}"
-          $ActionTest1SimpleFailureExpectedConclusion = "success"
-          $ActionTest1SimpleFailureConclusionResult = $ActionTest1SimpleFailureConclusion -eq $ActionTest1SimpleFailureExpectedConclusion
-          $ActionTest2StandardOutcome = "${{ needs.ActionTest2Standard.outputs.outcome }}"
-          $ActionTest2StandardExpectedOutcome = "success"
-          $ActionTest2StandardOutcomeResult = $ActionTest2StandardOutcome -eq $ActionTest2StandardExpectedOutcome
-          $ActionTest2StandardConclusion = "${{ needs.ActionTest2Standard.outputs.conclusion }}"
-          $ActionTest2StandardExpectedConclusion = "success"
-          $ActionTest2StandardConclusionResult = $ActionTest2StandardConclusion -eq $ActionTest2StandardExpectedConclusion
-          $ActionTest3AdvancedOutcome = "${{ needs.ActionTest3Advanced.outputs.outcome }}"
-          $ActionTest3AdvancedExpectedOutcome = "success"
-          $ActionTest3AdvancedOutcomeResult = $ActionTest3AdvancedOutcome -eq $ActionTest3AdvancedExpectedOutcome
-          $ActionTest3AdvancedConclusion = "${{ needs.ActionTest3Advanced.outputs.conclusion }}"
-          $ActionTest3AdvancedExpectedConclusion = "success"
-          $ActionTest3AdvancedConclusionResult = $ActionTest3AdvancedConclusion -eq $ActionTest3AdvancedExpectedConclusion
+      - name: Display Aggregated Results as a Table
+        uses: PSModule/Github-Script@v1
+        with:
+          Script: |
+            Install-PSResource -Name Markdown -Repository PSGallery -TrustRepository
 
+            # Build an array of objects for each job
+            $ActionTest1SimpleOutcome = "${{ needs.ActionTest1Simple.outputs.outcome }}"
+            $ActionTest1SimpleExpectedOutcome = "success"
+            $ActionTest1SimpleOutcomeResult = $ActionTest1SimpleOutcome -eq $ActionTest1SimpleExpectedOutcome
+            $ActionTest1SimpleConclusion = "${{ needs.ActionTest1Simple.outputs.conclusion }}"
+            $ActionTest1SimpleExpectedConclusion = "success"
+            $ActionTest1SimpleConclusionResult = $ActionTest1SimpleConclusion -eq $ActionTest1SimpleExpectedConclusion
+            $ActionTest1SimpleFailureOutcome = "${{ needs.ActionTest1SimpleFailure.outputs.outcome }}"
+            $ActionTest1SimpleFailureExpectedOutcome = "failure"
+            $ActionTest1SimpleFailureOutcomeResult = $ActionTest1SimpleFailureOutcome -eq $ActionTest1SimpleFailureExpectedOutcome
+            $ActionTest1SimpleFailureConclusion = "${{ needs.ActionTest1SimpleFailure.outputs.conclusion }}"
+            $ActionTest1SimpleFailureExpectedConclusion = "success"
+            $ActionTest1SimpleFailureConclusionResult = $ActionTest1SimpleFailureConclusion -eq $ActionTest1SimpleFailureExpectedConclusion
+            $ActionTest2StandardOutcome = "${{ needs.ActionTest2Standard.outputs.outcome }}"
+            $ActionTest2StandardExpectedOutcome = "success"
+            $ActionTest2StandardOutcomeResult = $ActionTest2StandardOutcome -eq $ActionTest2StandardExpectedOutcome
+            $ActionTest2StandardConclusion = "${{ needs.ActionTest2Standard.outputs.conclusion }}"
+            $ActionTest2StandardExpectedConclusion = "success"
+            $ActionTest2StandardConclusionResult = $ActionTest2StandardConclusion -eq $ActionTest2StandardExpectedConclusion
+            $ActionTest3AdvancedOutcome = "${{ needs.ActionTest3Advanced.outputs.outcome }}"
+            $ActionTest3AdvancedExpectedOutcome = "success"
+            $ActionTest3AdvancedOutcomeResult = $ActionTest3AdvancedOutcome -eq $ActionTest3AdvancedExpectedOutcome
+            $ActionTest3AdvancedConclusion = "${{ needs.ActionTest3Advanced.outputs.conclusion }}"
+            $ActionTest3AdvancedExpectedConclusion = "success"
+            $ActionTest3AdvancedConclusionResult = $ActionTest3AdvancedConclusion -eq $ActionTest3AdvancedExpectedConclusion
 
-          $jobs = @(
-            [PSCustomObject]@{
-              Name               = "ActionTest1Simple"
-              Outcome            = $ActionTest1SimpleOutcome
-              ExpectedOutcome    = $ActionTest1SimpleExpectedOutcome
-              PassedOutcome      = $ActionTest1SimpleOutcomeResult
-              Conclusion         = $ActionTest1SimpleConclusion
-              ExpectedConclusion = $ActionTest1SimpleExpectedConclusion
-              PassedConclusion   = $ActionTest1SimpleConclusionResult
-            },
-            [PSCustomObject]@{
-              Name               = "ActionTest1SimpleFailure"
-              Outcome            = $ActionTest1SimpleFailureOutcome
-              ExpectedOutcome    = $ActionTest1SimpleFailureExpectedOutcome
-              PassedOutcome      = $ActionTest1SimpleFailureOutcomeResult
-              Conclusion         = $ActionTest1SimpleFailureConclusion
-              ExpectedConclusion = $ActionTest1SimpleFailureExpectedConclusion
-              PassedConclusion   = $ActionTest1SimpleFailureConclusionResult
-            },
-            [PSCustomObject]@{
-              Name               = "ActionTest2Standard"
-              Outcome            = $ActionTest2StandardOutcome
-              ExpectedOutcome    = $ActionTest2StandardExpectedOutcome
-              PassedOutcome      = $ActionTest2StandardOutcomeResult
-              Conclusion         = $ActionTest2StandardConclusion
-              ExpectedConclusion = $ActionTest2StandardExpectedConclusion
-              PassedConclusion   = $ActionTest2StandardConclusionResult
-            },
-            [PSCustomObject]@{
-              Name               = "ActionTest3Advanced"
-              Outcome            = $ActionTest3AdvancedOutcome
-              ExpectedOutcome    = $ActionTest3AdvancedExpectedOutcome
-              PassedOutcome      = $ActionTest3AdvancedOutcomeResult
-              Conclusion         = $ActionTest3AdvancedConclusion
-              ExpectedConclusion = $ActionTest3AdvancedExpectedConclusion
-              PassedConclusion   = $ActionTest3AdvancedConclusionResult
+            $jobs = @(
+              [PSCustomObject]@{
+                Name               = "Action-Test - [1-Simple]"
+                Outcome            = $ActionTest1SimpleOutcome
+                ExpectedOutcome    = $ActionTest1SimpleExpectedOutcome
+                PassedOutcome      = $ActionTest1SimpleOutcomeResult
+                Conclusion         = $ActionTest1SimpleConclusion
+                ExpectedConclusion = $ActionTest1SimpleExpectedConclusion
+                PassedConclusion   = $ActionTest1SimpleConclusionResult
+              },
+              [PSCustomObject]@{
+                Name               = "Action-Test - [1-Simple-Failure]"
+                Outcome            = $ActionTest1SimpleFailureOutcome
+                ExpectedOutcome    = $ActionTest1SimpleFailureExpectedOutcome
+                PassedOutcome      = $ActionTest1SimpleFailureOutcomeResult
+                Conclusion         = $ActionTest1SimpleFailureConclusion
+                ExpectedConclusion = $ActionTest1SimpleFailureExpectedConclusion
+                PassedConclusion   = $ActionTest1SimpleFailureConclusionResult
+              },
+              [PSCustomObject]@{
+                Name               = "Action-Test - [2-Standard]"
+                Outcome            = $ActionTest2StandardOutcome
+                ExpectedOutcome    = $ActionTest2StandardExpectedOutcome
+                PassedOutcome      = $ActionTest2StandardOutcomeResult
+                Conclusion         = $ActionTest2StandardConclusion
+                ExpectedConclusion = $ActionTest2StandardExpectedConclusion
+                PassedConclusion   = $ActionTest2StandardConclusionResult
+              },
+              [PSCustomObject]@{
+                Name               = "Action-Test - [3-Advanced]"
+                Outcome            = $ActionTest3AdvancedOutcome
+                ExpectedOutcome    = $ActionTest3AdvancedExpectedOutcome
+                PassedOutcome      = $ActionTest3AdvancedOutcomeResult
+                Conclusion         = $ActionTest3AdvancedConclusion
+                ExpectedConclusion = $ActionTest3AdvancedExpectedConclusion
+                PassedConclusion   = $ActionTest3AdvancedConclusionResult
+              }
+            )
+
+            # Display the table in the workflow logs
+            $jobs | Format-List
+
+            $passed = $true
+            $jobs | ForEach-Object {
+              if (-not $_.PassedOutcome) {
+                Write-Error "Job $($_.Name) failed with Outcome $($_.Outcome) and Expected Outcome $($_.ExpectedOutcome)"
+                $passed = $false
+              }
+
+              if (-not $_.PassedConclusion) {
+                Write-Error "Job $($_.Name) failed with Conclusion $($_.Conclusion) and Expected Conclusion $($_.ExpectedConclusion)"
+                $passed = $false
+              }
             }
-          )
 
-          # Display the table in the workflow logs
-          $jobs | Format-List
-
-          $passed = $true
-          $jobs | ForEach-Object {
-            if (-not $_.PassedOutcome) {
-              Write-Error "Job $($_.Name) failed with Outcome $($_.Outcome) and Expected Outcome $($_.ExpectedOutcome)"
-              $passed = $false
+            $icon = if ($passed) { '✅' } else { '❌' }
+            $status = Heading 1 "$icon - GitHub Actions Status" {
+                Table {
+                    $jobs
+                }
             }
 
-            if (-not $_.PassedConclusion) {
-              Write-Error "Job $($_.Name) failed with Conclusion $($_.Conclusion) and Expected Conclusion $($_.ExpectedConclusion)"
-              $passed = $false
-            }
-          }
+            Set-GitHubStepSummary -Summary $status
 
-          if (-not $passed) {
-            Write-GithubError "One or more jobs failed"
-            exit 1
-          }
+            if (-not $passed) {
+              Write-GithubError "One or more jobs failed"
+              exit 1
+            }
